apiVersion: v1
kind: Namespace
metadata:
  name: subway
  labels:
    name: subway-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: subway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: subway
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - pods
      - deployments
      - namespaces
      - pods
      - replicasets
      - serviceaccounts
      - services
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: subway 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-role
subjects:
- namespace: subway 
  kind: ServiceAccount
  name: jenkins
