apiVersion: apps/v1
kind: Deployment
metadata:
  name: subway-deployment
  namespace: subway
  labels:
    app: subway-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: subway-prod
  template:
    metadata:
      labels:
        app: subway-prod
    spec:
      containers:
      - name: subway-cont
        image: soravkumarsharma/subway-surfers:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: subway-svc
  namespace: subway
spec:
  type: NodePort
  selector:
    app: subway-prod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
